### ISSUE TITLE
A small problem with the links on coding challenges

### ISSUE THREAD

**Issue by Heinrich-XIAO** [CodingTrain/thecodingtrain.com#144] opened 2022-05-26 00:52 UTC
When you click on the words on a coding challenge, it goes to /tracks/thecodingchallenge.

**Comment by shiffman** [comment] 2022-06-01 14:10
Can you give a specific example? I can't reproduce this.

**Comment by shiffman** [comment] 2022-06-02 13:44
Great! I'm going to close this issue @Heinrich-XIAO please let us know if you still find a problem, thank you!!!

**Closed by shiffman** 2022-06-02 13:44 UTC
